some changes that doesn't help

diff --git a/platform/Dockerfile b/platform/Dockerfile
--- a/platform/Dockerfile
+++ b/platform/Dockerfile
@@ -1,37 +1,147 @@
-FROM python:3.11-slim-buster as prod
+# Dockerfile
+# Uses multi-stage builds requiring Docker 17.05 or higher
+# See https://docs.docker.com/develop/develop-images/multistage-build/
 
-RUN apt-get update && apt-get install -y \
-  default-libmysqlclient-dev \
-  gcc \
-  pkg-config \
-  openjdk-11-jdk \
-  build-essential \
-  && rm -rf /var/lib/apt/lists/*
+# Creating a python base with shared environment variables
+FROM python:3.11-slim-bullseye AS python-base
+ENV PYTHONUNBUFFERED=1 \
+    PYTHONDONTWRITEBYTECODE=1 \
+    PIP_NO_CACHE_DIR=off \
+    PIP_DISABLE_PIP_VERSION_CHECK=on \
+    PIP_DEFAULT_TIMEOUT=100 \
+    POETRY_HOME="/opt/poetry" \
+    POETRY_VIRTUALENVS_IN_PROJECT=true \
+    POETRY_NO_INTERACTION=1 \
+    PYSETUP_PATH="/opt/pysetup" \
+    VENV_PATH="/opt/pysetup/.venv"
 
-RUN pip install poetry==1.4.2
+ENV PATH="$POETRY_HOME/bin:$VENV_PATH/bin:$PATH"
 
-# Configuring poetry
-RUN poetry config virtualenvs.create false
+# builder-base is used to build dependencies
+FROM python-base AS builder-base
+RUN buildDeps="build-essential" \
+    && apt-get update \
+    && apt-get install --no-install-recommends -y \
+        curl \
+        vim \
+        netcat \
+        default-libmysqlclient-dev \
+        pkg-config \
+        gcc \
+        pkg-config \
+        libpq-dev \
+    && apt-get install -y --no-install-recommends $buildDeps \
+    && rm -rf /var/lib/apt/lists/*
 
-# Copying requirements of a project
-COPY pyproject.toml /app/src/
-WORKDIR /app/src
 
-# Installing requirements
-RUN poetry install --only main
+
+
+# Install Poetry - respects $POETRY_VERSION & $POETRY_HOME
+ENV POETRY_VERSION=1.7.0
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+
+RUN pip3 install --upgrade pip setuptools wheel
+
+RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=${POETRY_HOME} python3 - --version ${POETRY_VERSION} && \
+    chmod a+x /opt/poetry/bin/poetry \
+
+RUN poetry --version
+#config virtualenvs.create false --local
+#RUN pip3 install --upgrade pip setuptools wheel
+#
+##RUN pip3 install poetry==$POETRY_VERSION
+#RUN pip3 wheel --use-pep517 "jpype1 (==1.4.1)"
+#RUN pip3 wheel --use-pep517 "mysqlclient (==2.2.0)"
+
+#RUN poetry config virtualenvs.create false --local
+
+
+# We copy our Python requirements here to cache them
+# and install only runtime deps using poetry
+WORKDIR $PYSETUP_PATH
+COPY  ./pyproject.toml ./
+RUN poetry install --only main  # respects
+
 # Removing gcc
 RUN apt-get purge -y \
   g++ \
   gcc \
+  && rm -rf /var/lib/apt/lists/* ֿֿֿ
+#  pkg-config \
+
+
+# 'development' stage installs all dev deps and can be used to develop code.
+# For example using docker-compose to mount local volume under /app
+FROM python-base as development
+ENV FASTAPI_ENV=development
+
+RUN apt-get update && apt-get install -y \
+  default-libmysqlclient-dev \
+  pkg-config \
+  gcc \
   pkg-config \
   && rm -rf /var/lib/apt/lists/*
 
-# Copying actual application
-COPY . /app/src/
-RUN poetry install --only main
+# Copying poetry and venv into image
+COPY --from=builder-base $POETRY_HOME $POETRY_HOME
+COPY --from=builder-base $PYSETUP_PATH $PYSETUP_PATH
 
-CMD ["/usr/local/bin/python", "-m", "reworkd_platform"]
+# Copying in our entrypoint
+COPY docker-entrypoint.sh /docker-entrypoint.sh
+RUN chmod +x /docker-entrypoint.sh
 
-FROM prod as dev
-
+# venv already has runtime deps installed we get a quicker install
+WORKDIR $PYSETUP_PATH
 RUN poetry install
+RUN poetry add langchain@latest
+WORKDIR /app
+
+COPY . .
+RUN poetry install --sync
+#RUN poetry add reworkd_platform@latest
+RUN poetry install
+RUN poetry build
+
+EXPOSE 8000
+COPY  ./pyproject.toml ./
+
+
+ENTRYPOINT /docker-entrypoint.sh $0 $@
+
+CMD ["uvicorn", "--reload", "--host=0.0.0.0", "--port=8000", "app.reworkd_platform.web.application:get_app"]
+#CMD ["poetry", "run", "reworkd_platform"]
+
+# 'lint' stage runs black and isort
+# running in check mode means build will fail if any linting errors occur
+FROM development AS lint
+RUN black --config ./pyproject.toml --check app tests
+RUN isort --settings-path ./pyproject.toml --recursive --check-only
+CMD ["tail", "-f", "/dev/null"]
+
+# 'test' stage runs our unit tests with pytest and
+# coverage.  Build will fail if test coverage is under 95%
+FROM development AS test
+RUN coverage run --rcfile ./pyproject.toml -m pytest ./tests
+RUN coverage report --fail-under 95
+
+# 'production' stage uses the clean 'python-base' stage and copyies
+# in only our runtime deps that were installed in the 'builder-base'
+FROM python-base AS production
+ENV FASTAPI_ENV=production
+
+COPY --from=builder-base $VENV_PATH $VENV_PATH
+COPY gunicorn_conf.py /gunicorn_conf.py
+
+COPY docker-entrypoint.sh /docker-entrypoint.sh
+RUN chmod +x /docker-entrypoint.sh
+
+# Create user with the name poetry
+RUN groupadd -g 1500 poetry && \
+    useradd -m -u 1500 -g poetry poetry
+
+COPY --chown=poetry:poetry ./app /app
+USER poetry
+WORKDIR /app
+
+ENTRYPOINT /docker-entrypoint.sh $0 $@
+CMD [ "gunicorn", "--worker-class uvicorn.workers.UvicornWorker", "--config /gunicorn_conf.py", "reworkd_platform.web.application:get_app"]
